"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SaeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRAME_FIELD_NUMBER: builtins.int
    DETECTIONS_FIELD_NUMBER: builtins.int
    TRAJECTORY_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    @property
    def frame(self) -> global___VideoFrame: ...
    @property
    def detections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Detection]: ...
    @property
    def trajectory(self) -> global___Trajectory: ...
    @property
    def metrics(self) -> global___Metrics: ...
    def __init__(
        self,
        *,
        frame: global___VideoFrame | None = ...,
        detections: collections.abc.Iterable[global___Detection] | None = ...,
        trajectory: global___Trajectory | None = ...,
        metrics: global___Metrics | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["frame", b"frame", "metrics", b"metrics", "trajectory", b"trajectory"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["detections", b"detections", "frame", b"frame", "metrics", b"metrics", "trajectory", b"trajectory"]) -> None: ...

global___SaeMessage = SaeMessage

@typing.final
class VideoFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_UTC_MS_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    FRAME_DATA_FIELD_NUMBER: builtins.int
    FRAME_DATA_JPEG_FIELD_NUMBER: builtins.int
    source_id: builtins.str
    timestamp_utc_ms: builtins.int
    frame_data: builtins.bytes
    frame_data_jpeg: builtins.bytes
    @property
    def shape(self) -> global___Shape: ...
    def __init__(
        self,
        *,
        source_id: builtins.str = ...,
        timestamp_utc_ms: builtins.int = ...,
        shape: global___Shape | None = ...,
        frame_data: builtins.bytes = ...,
        frame_data_jpeg: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["shape", b"shape"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["frame_data", b"frame_data", "frame_data_jpeg", b"frame_data_jpeg", "shape", b"shape", "source_id", b"source_id", "timestamp_utc_ms", b"timestamp_utc_ms"]) -> None: ...

global___VideoFrame = VideoFrame

@typing.final
class Shape(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEIGHT_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    height: builtins.int
    width: builtins.int
    channels: builtins.int
    def __init__(
        self,
        *,
        height: builtins.int = ...,
        width: builtins.int = ...,
        channels: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "height", b"height", "width", b"width"]) -> None: ...

global___Shape = Shape

@typing.final
class Detection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOUNDING_BOX_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    CLASS_ID_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    GEO_COORDINATE_FIELD_NUMBER: builtins.int
    FEATURE_FIELD_NUMBER: builtins.int
    confidence: builtins.float
    class_id: builtins.int
    object_id: builtins.int
    @property
    def bounding_box(self) -> global___BoundingBox: ...
    @property
    def geo_coordinate(self) -> global___GeoCoordinate: ...
    @property
    def feature(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Ensure this line is added"""

    def __init__(
        self,
        *,
        bounding_box: global___BoundingBox | None = ...,
        confidence: builtins.float = ...,
        class_id: builtins.int = ...,
        object_id: builtins.int = ...,
        geo_coordinate: global___GeoCoordinate | None = ...,
        feature: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bounding_box", b"bounding_box", "geo_coordinate", b"geo_coordinate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bounding_box", b"bounding_box", "class_id", b"class_id", "confidence", b"confidence", "feature", b"feature", "geo_coordinate", b"geo_coordinate", "object_id", b"object_id"]) -> None: ...

global___Detection = Detection

@typing.final
class BoundingBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIN_X_FIELD_NUMBER: builtins.int
    MIN_Y_FIELD_NUMBER: builtins.int
    MAX_X_FIELD_NUMBER: builtins.int
    MAX_Y_FIELD_NUMBER: builtins.int
    TIMESTAMP_UTC_MS_FIELD_NUMBER: builtins.int
    min_x: builtins.float
    min_y: builtins.float
    max_x: builtins.float
    max_y: builtins.float
    timestamp_utc_ms: builtins.int
    def __init__(
        self,
        *,
        min_x: builtins.float = ...,
        min_y: builtins.float = ...,
        max_x: builtins.float = ...,
        max_y: builtins.float = ...,
        timestamp_utc_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_x", b"max_x", "max_y", b"max_y", "min_x", b"min_x", "min_y", b"min_y", "timestamp_utc_ms", b"timestamp_utc_ms"]) -> None: ...

global___BoundingBox = BoundingBox

@typing.final
class GeoCoordinate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    latitude: builtins.float
    longitude: builtins.float
    def __init__(
        self,
        *,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["latitude", b"latitude", "longitude", b"longitude"]) -> None: ...

global___GeoCoordinate = GeoCoordinate

@typing.final
class Metrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DETECTION_INFERENCE_TIME_US_FIELD_NUMBER: builtins.int
    TRACKING_INFERENCE_TIME_US_FIELD_NUMBER: builtins.int
    FEATURE_EXTRACTION_TIME_US_FIELD_NUMBER: builtins.int
    MERGE_INFERENCE_TIME_US_FIELD_NUMBER: builtins.int
    detection_inference_time_us: builtins.int
    tracking_inference_time_us: builtins.int
    feature_extraction_time_us: builtins.int
    merge_inference_time_us: builtins.int
    def __init__(
        self,
        *,
        detection_inference_time_us: builtins.int = ...,
        tracking_inference_time_us: builtins.int = ...,
        feature_extraction_time_us: builtins.int = ...,
        merge_inference_time_us: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["detection_inference_time_us", b"detection_inference_time_us", "feature_extraction_time_us", b"feature_extraction_time_us", "merge_inference_time_us", b"merge_inference_time_us", "tracking_inference_time_us", b"tracking_inference_time_us"]) -> None: ...

global___Metrics = Metrics

@typing.final
class Trajectory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CamerasEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___TrackletsByCamera: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___TrackletsByCamera | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CAMERAS_FIELD_NUMBER: builtins.int
    @property
    def cameras(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___TrackletsByCamera]: ...
    def __init__(
        self,
        *,
        cameras: collections.abc.Mapping[builtins.str, global___TrackletsByCamera] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cameras", b"cameras"]) -> None: ...

global___Trajectory = Trajectory

@typing.final
class TrackletsByCamera(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TrackletsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Tracklet: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Tracklet | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TRACKLETS_FIELD_NUMBER: builtins.int
    @property
    def tracklets(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Tracklet]: ...
    def __init__(
        self,
        *,
        tracklets: collections.abc.Mapping[builtins.str, global___Tracklet] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tracklets", b"tracklets"]) -> None: ...

global___TrackletsByCamera = TrackletsByCamera

@typing.final
class Tracklet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEAN_FEATURE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    ENTRY_ZONE_FIELD_NUMBER: builtins.int
    EXIT_ZONE_FIELD_NUMBER: builtins.int
    DETECTIONS_INFO_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    MOTION_VECTOR_FIELD_NUMBER: builtins.int
    status: builtins.str
    start_time: builtins.int
    end_time: builtins.int
    entry_zone: builtins.str
    exit_zone: builtins.str
    age: builtins.int
    @property
    def mean_feature(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def detections_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Detection]: ...
    @property
    def motion_vector(self) -> global___MotionVector: ...
    def __init__(
        self,
        *,
        mean_feature: collections.abc.Iterable[builtins.float] | None = ...,
        status: builtins.str = ...,
        start_time: builtins.int = ...,
        end_time: builtins.int = ...,
        entry_zone: builtins.str = ...,
        exit_zone: builtins.str = ...,
        detections_info: collections.abc.Iterable[global___Detection] | None = ...,
        age: builtins.int = ...,
        motion_vector: global___MotionVector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["motion_vector", b"motion_vector"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["age", b"age", "detections_info", b"detections_info", "end_time", b"end_time", "entry_zone", b"entry_zone", "exit_zone", b"exit_zone", "mean_feature", b"mean_feature", "motion_vector", b"motion_vector", "start_time", b"start_time", "status", b"status"]) -> None: ...

global___Tracklet = Tracklet

@typing.final
class MotionVector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y"]) -> None: ...

global___MotionVector = MotionVector
