[tool.poetry]
name = "visionapi-yq"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
protobuf = "^5.27.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
